### ISSUE TITLE
Update for Nuxt3

### ISSUE THREAD

**Issue by A-linea** [ziaadini/nuxt-perfect-cache#19]
Good afternoon, will there be any further updates for Nuxt 3?
Currently with "nuxt:"^3.4.2", when adding to modules of this package, and `npm run dev` command an error is displayed:

` ERROR  Cannot restart nuxt:  Cannot destructure property 'nuxt' of 'this' as it is undefined. 
 at index (node_modules/nuxt-perfect-cache/index.js:12:11)
 at installModule (node_modules/@nuxt/kit/dist/index.mjs:450:101)
 at async initNuxt (node_modules/nuxt/dist/index.mjs:2617:7)
 at async load (node_modules/nuxi/dist/chunks/dev.mjs:183:9)
 at async _applyPromised (node_modules/nuxi/dist/chunks/dev.mjs:96:10)
`

Thank you for this package! Unfortunately, it is no longer compatible with the current version of Nuxt 3

**Comment by ziaadini** [comment]
Hello, there is no plan for upgrade to nuxt3 because, nuxt 3 is going to implement `ISG` **Incremental Static Generation** 
the trick is generate static pages in background and show static generated pages in each user request
