### ISSUE TITLE
Cannot read property 'headers' of undefined 

### ISSUE THREAD

**Issue by devzom** [ziaadini/nuxt-perfect-cache#4]
Hey, 
plugin seems to work on dev mode, but when trying to use 'nuxt generate' I am getting
`Cannot read property 'headers' of undefined                                                                                                                                                        

  at Server.renderer.renderRoute (node_modules/nuxt-perfect-cache/index.js:17:32)
  at Generator.afterGenerate (node_modules/@nuxt/generator/dist/generator.js:314:43)
  at async Generator.generate (node_modules/@nuxt/generator/dist/generator.js:141:5)
  at async Object.run (node_modules/@nuxt/cli/dist/cli-generate.js:376:24)
  at async NuxtCommand.run (node_modules/@nuxt/cli/dist/cli-index.js:2803:7)`

 error

seems that it's plugin responsibility for this. Any idead?

**Comment by ziaadini** [comment]
hello, there is no problem with plugin `ssg` doesn't need caching because nuxt mock all of server side requests during build process

**Comment by devzom** [comment]
OKey, I see the point, I managed it is working, thank You :)
