### ISSUE TITLE
ERROR  Stream connection ended and command aborted.

### ISSUE THREAD

**Issue by workingxx92** [ziaadini/nuxt-perfect-cache#8]
ERROR  Stream connection ended and command aborted.

  at RedisClient.flush_and_error (node_modules/redis/index.js:298:23)
  at RedisClient.connection_gone (node_modules/redis/index.js:533:14)
  at Socket.<anonymous> (node_modules/redis/index.js:227:14)
  at Object.onceWrapper (events.js:482:26)
  at Socket.emit (events.js:375:28)
  at TCP.<anonymous> (net.js:675:12)

 ERROR  Stream connection ended and command aborted.

  at RedisClient.flush_and_error (node_modules/redis/index.js:298:23)
  at RedisClient.connection_gone (node_modules/redis/index.js:533:14)
  at Socket.<anonymous> (node_modules/redis/index.js:227:14)
  at Object.onceWrapper (events.js:482:26)
  at Socket.emit (events.js:375:28)
  at TCP.<anonymous> (net.js:675:12)

 ERROR  Stream connection ended and command aborted.

  at RedisClient.flush_and_error (node_modules/redis/index.js:298:23)
  at RedisClient.connection_gone (node_modules/redis/index.js:533:14)
  at Socket.<anonymous> (node_modules/redis/index.js:227:14)
  at Object.onceWrapper (events.js:482:26)
  at Socket.emit (events.js:375:28)
  at TCP.<anonymous> (net.js:675:12)

**Comment by devzom** [comment]
What's Your redis address? I had similar issue when I've provider wrong address.

**Comment by workingxx92** [comment]
HI @devzom 
Please tell me what's Redis address?
redis://127.0.0.1:6379 ?

**Comment by devzom** [comment]
> HI @devzom
> Please tell me what's Redis address?
> redis://127.0.0.1:6379 ?


Are You sure redis instance is alive on Your system? have You checked it? port 6379 is the default one, but maybe You've changed it or just the instance is not available on this address. 
I'm using a Docker infrastructure with proxy so I have it available under other address and port.

**Comment by workingxx92** [comment]
@devzom 
redis is alive on my system

**Comment by ziaadini** [comment]
i think the problem is about your redis config it works in my laptop and in all of my projects normally

**Comment by sonnd08** [comment]
This happens to us recently, redis still alive in the time we check. After restart frontend, it starts connecting normally.
